# Generated by Django 5.1.4 on 2024-12-13 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motive',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.UUID('7d7e669d-50af-4580-8929-aa2fd0078c70'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(upload_to='image/motive/logo/')),
                ('motive_type', models.CharField(choices=[('Social Cause', 'Social Cause'), ('Environmental', 'Environmental'), ('Educational', 'Educational'), ('Medical', 'Medical'), ('Charity', 'Charity'), ('Other', 'Other')], default='Social Cause', max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.UUID('b750b2b5-8c28-41fc-b153-c99ae09d180e'), primary_key=True, serialize=False)),
                ('dp', models.ImageField(upload_to='image/group/dp/')),
                ('name', models.CharField(default=models.UUIDField(auto_created=True, default=uuid.UUID('b750b2b5-8c28-41fc-b153-c99ae09d180e'), primary_key=True, serialize=False), max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('motive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.motive')),
            ],
        ),
        migrations.CreateModel(
            name='IniatatorGroupContributor',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.UUID('5f1719dc-1727-42f5-ad98-bf6e651a748d'), primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Creator', 'Creator'), ('User', 'User')], default='User', max_length=50)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.group')),
            ],
            options={
                'unique_together': {('contributor', 'group')},
            },
        ),
    ]
